### ISSUE TITLE
最低计费重量更改

### ISSUE THREAD

**Issue by corapica405** [bensom1989/SHL#12]
请把计费中，最低计费重量改为5公斤

**Comment by maxbchyper** [comment]
这个最低重量是指的一个人当前批次的所有箱单的重量合（每个箱单的重量都用体积重和实际重量取最大值）低于五公斤的话，按照五公斤计算总价格（也需要把这个价格让客户来出，也要平均改变每一个箱单的价格）一般来说这种情况是只有一个小包裹，不存在多的箱单，但还是加一个逻辑，防止价格溢出

**Comment by bensom1989** [comment]
需求确认好后重开吧
