### ISSUE TITLE
箱单号有两个按钮

### ISSUE THREAD

**Issue by maxbchyper** [bensom1989/SHL#16]
![image](https://user-images.githubusercontent.com/96399686/155657729-a8a27767-b776-40fb-aa5c-40d3b42f4bb1.png)
这两个按钮有歧义，希望一个只是保存，另外一个保存退出，跳转回list页面

并且所有下面搜索到之后，选中的数据，已经跳转到上面的时候，下面可以看不到

**Comment by bensom1989** [comment]
not bug
