### ISSUE TITLE
箱单页面按钮功能分开

### ISSUE THREAD

**Issue by maxbchyper** [bensom1989/SHL#28]
箱单绑定订单的页面，左中的按钮和右上的按钮功能应当有区别，一个只保存订单，另外一个才会跳出新的窗口来保存实际重量，箱子大小等信息

**Comment by bensom1989** [comment]
现在不就是这样么

**Comment by maxbchyper** [comment]
![image](https://user-images.githubusercontent.com/96399686/174692068-82c664e3-d942-4e12-857e-aaad5525176e.png)
左边的确认绑定按钮点击后不出现第二个框，只是做订单的保存

**Comment by bensom1989** [comment]
fixxed
