### ISSUE TITLE
批次号生成规则修改

### ISSUE THREAD

**Issue by maxbchyper** [bensom1989/SHL#30]
根据选择运货公司的不同，创建批次号的时候最后加上这个货运公司的缩写

**Comment by jeawy** [comment]
举例子

**Comment by maxbchyper** [comment]
![image](https://user-images.githubusercontent.com/96399686/174692506-f35d18c2-3fc4-4c76-9bfc-e5f55eb2052e.png)
供应商增加简写，简写英文字母放在批次号前面，他们说的第三个是空运A开头（A20220621），第二个是海运S开头（S20220621），但是为了避免出现第三个供应商，可能需要一个新逻辑
