### ISSUE TITLE
关于系统箱单状态显示问题

### ISSUE THREAD

**Issue by corapica405** [bensom1989/SHL#38]
状态显示属性有下面几种：未封箱，待启运，已启运，已到港，待查验，已清关，已到仓，已收货
支付显示属性有两种：未支付，已支付

之前我们说的是在批次状态更改，是否直接在箱单这里加入批量更改状态更方便，如下图，增加一些按钮
或者直接做个下拉菜单，可以批量选择状态

![image](https://user-images.githubusercontent.com/99375531/192686100-660bed2e-6d44-4478-b0cb-9d4367786e95.png)

**Comment by bensom1989** [comment]
已完成
