### ISSUE TITLE
【修改】导出表格信息地址不全的问题

### ISSUE THREAD

**Issue by corapica405** [bensom1989/SHL#43]
**1. 添加收货地址时，除地区/State以外，其余为必填项（Required）**

![image](https://user-images.githubusercontent.com/99375531/197685440-492c8f1e-fe66-4440-afe3-77a235367e22.png)

**2. 导出表格时，两个表格在地址后均添加两列（地区/Suburb）和（邮编/Postcode）**

![image](https://user-images.githubusercontent.com/99375531/197685919-7183bc9f-1155-4ba8-9d37-49f229c5c886.png)
![image](https://user-images.githubusercontent.com/99375531/197686010-e6da4793-78d1-4359-a37c-21c284470a53.png)

**Comment by bensom1989** [comment]
![image](https://user-images.githubusercontent.com/91407062/198860689-48a36342-b99e-45ab-a309-daefd0b9f6db.png)

**Comment by bensom1989** [comment]
![image](https://user-images.githubusercontent.com/91407062/198862899-94053dc2-6881-4fa5-9620-a78dcb6748a6.png)

**Comment by bensom1989** [comment]
![image](https://user-images.githubusercontent.com/91407062/198862908-3b6e6977-b636-4b77-bd15-9390f5f1e9fd.png)
