### ISSUE TITLE
设置页面

### ISSUE THREAD

**Issue by maxbchyper** [bensom1989/SHL#7]
需要一个额外的设置页面，其中包括：
1 箱型可以更改和新建，每个箱子的成本费也要加进来
2 新建批次号里的默认供应商，起运港和目的港都可以更改
3 汇率可以更改 （货值导出的时候默认都是澳币，但是客户输入可以是人民币或者美元，需要计算成澳币）

**Comment by bensom1989** [comment]
箱型管理已添加
第二条默认已完成
3 条待完善需求
